name: Daily Email Report with AI-Agent

on:
  schedule:
    # Run at 6:00 AM UTC = 8:00 AM Egypt
    - cron: "0 6 * * 0-4"   # Sunday → Thursday only
  workflow_dispatch:      # allow manual trigger

jobs:
  send-email:
    runs-on: ubuntu-latest
    env:
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
    steps:
      - name: Checkout repo 
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Run script
        run: python main.py
